const fs=require('node:fs/promises');
const path=require('node:path');
async function main(){
 const out=path.resolve('output/portfolio-demo');
 await fs.cp('web/public/font-licenses',path.join(out,'font-licenses'),{recursive:true});
 for(const name of ['product','technical','loop']){
  require('node:child_process').execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-y','-ss','1','-i',path.join(out,name+'.mp4'),'-frames:v','1',path.join(out,'assets',name+'-poster.png')]);
 }
 const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DATA:EZ · 포트폴리오 데모</title><style>@font-face{font-family:Spoqa;src:url(fonts/spoqa.ttf)}*{box-sizing:border-box}body{margin:0;background:#171b20;color:#f2f4f7;font-family:Spoqa,system-ui;padding:52px 5vw 90px}main{max-width:1500px;margin:auto}header{display:flex;justify-content:space-between;gap:30px;align-items:start}small{color:#82b4ff}h1{font-size:38px;letter-spacing:-.04em;margin:14px 0}p{line-height:1.8;color:#afb9c7}a{color:#82b4ff;text-underline-offset:5px}nav{display:flex;gap:20px;flex-wrap:wrap;padding:22px 0;border-bottom:1px solid #3b4552}section{margin-top:48px}section h2{font-size:23px;margin-bottom:12px}video{display:block;width:100%;background:#111418;border:1px solid #3b4552;border-radius:10px}footer{margin-top:55px;border-top:1px solid #3b4552;padding-top:24px;font-size:14px}.downloads{display:flex;gap:22px;flex-wrap:wrap;margin-top:16px}.meta{font-size:14px}button{font:inherit;background:#293446;color:#d7e8ff;border:1px solid #4a6080;border-radius:8px;padding:10px 14px;cursor:pointer}@media(max-width:700px){body{padding:25px 18px}header{display:block}h1{font-size:29px}}</style><main><header><div><small>DATA:EZ · PORTFOLIO DEMO</small><h1>파일에서 통계로, 내 대시보드로.</h1><p>실제 공개 앱과 모델을 사용해 촬영한 데모입니다.<br>무음 자막형 · 합성 매출 데이터 · 2026.09.12 촬영</p></div><a href="https://dataez.vercel.app/" target="_blank" rel="noreferrer">서비스 열기 ↗</a></header><nav><a href="#product">제품 데모 · 1:50</a><a href="#technical">기술 설명 · 5:00</a><a href="#loop">반복 영상 · 0:12</a></nav>
${[['product','제품 데모','질문에서 정확한 집계표, 저장과 재접속까지.','1:50'],['technical','기술 설명','원본과 누적 장부의 차이, SQL과 현재 배포 구조.','5:00'],['loop','12초 반복 영상','실제 질문 → 차트 → 저장 결과를 짧게 편집했습니다.','0:12']].map(([id,title,desc,time])=>`<section id="${id}"><h2>${title} <small>${time}</small></h2><p>${desc}</p><video id="video-${id}" controls playsinline preload="metadata" ${id==='loop'?'loop muted':''} poster="assets/${id}-poster.png"><source src="${id==='loop'?'loop.webm':id+'.mp4'}" type="${id==='loop'?'video/webm':'video/mp4'}"></video><div class="downloads"><a href="${id}.mp4" download>MP4 다운로드</a>${id==='loop'?'<a href="loop.webm" download>WebM 다운로드</a>':''}<a href="${id}.ko.srt" download>한국어 SRT</a><button onclick="document.getElementById('video-${id}').requestFullscreen()">전체 화면</button></div></section>`).join('')}
<footer><p>모든 영상에 한국어 자막이 포함되어 있습니다. 작은 글씨는 전체 화면으로 보세요. 로그인은 녹화에서 제외했고, 계정 표시만 가렸습니다. 커서 강조, 읽기용 화면 정지·부분 확대와 일부 조작 구간의 속도 조정(최대 약 1.05배)이 포함된 편집본입니다.</p><p>원본 집계표 합계 690,200원 · 데모 거래 30,000원 1회 추가 후 누적 720,200원. 거래 추가는 API 준비 작업이며 실제 PG 자동 수집이 아닙니다. 기술 영상의 구조도는 동작 설명 화면입니다.</p><a href="https://github.com/gnb1202/DATAEZ" target="_blank" rel="noreferrer">구현과 검증 기록 ↗</a></footer></main></html>`;
 await fs.writeFile(path.join(out,'index.html'),html);console.log('Preview ready');
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
